apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mateo-spotify-backend-ingress
  namespace: $NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mateo-spotify-api.duckdns.org
    secretName: api-tls-secret
  rules:
  - host: mateo-spotify-api.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mateo-spotify-backend
            port:
              number: 8080
