services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=mateo-spotify.duckdns.org
      - VALIDATION=dns
      - ONLY_SUBDOMAINS=false
      - DNSPLUGIN=duckdns
      - PROPAGATION_SECONDS=60
      - dns_duckdns_propagation_seconds=60
      - DUCKDNSTOKEN=ed68963f-3014-479d-aba7-6484727b28e8
      - dns_duckdns_token=ed68963f-3014-479d-aba7-6484727b28e8

    volumes:
      - ./swag/swag-config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
