name: Build and Deploy Docker Images & Apply Kubernetes Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Enable Corepack
        run: corepack enable

      - name: Install frontend dependencies
        run: cd app/client && pnpm install --frozen-lockfile

      - name: Run ESLint
        run: cd app/client && pnpm lint

      - name: Set DOTNET_ROOT
        run: |
          DOTNET_PATH=$(readlink -f $(which dotnet))
          DOTNET_DIR=$(dirname $DOTNET_PATH)
          echo "DOTNET_ROOT=$DOTNET_DIR" >> $GITHUB_ENV

      - name: Restore backend dependencies
        run: cd app/server && dotnet restore

      - name: Build backend
        run: cd app/server && dotnet build --no-restore

      - name: Run backend tests
        run: cd app/server && dotnet test --no-build --verbosity normal

  build-and-push:
    needs: lint-and-test
    runs-on: self-hosted
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: |
          docker buildx build --platform linux/amd64 \
          --build-arg VITE_KEYCLOAK_CLIENT_ID=mateo-spotify-agent \
          --build-arg VITE_KEYCLOAK_AUTHORITY=https://auth-dev.snowse.io/realms/DevRealm \
          --build-arg VITE_KEYCLOAK_JWKS_URI=https://auth-dev.snowse.io/realms/DevRealm/protocol/openid-connect/certs \
          --build-arg VITE_API_URL=http://api.mateo-spotify.duckdns.org \
          --build-arg VITE_SPOTIFY_CLIENT_ID=83a1fa87b8ff4bff8390fa70d2b95d9c \
          --build-arg VITE_SPOTIFY_REDIRECT_URI=https://mateo-spotify.duckdns.org/settings \
          -f ./dockerfiles/Dockerfile.client \
          -t ${{ secrets.DOCKER_USERNAME }}/spotify-frontend:${{ github.run_number }} \
          .

      - name: Build backend image
        run: |
          docker buildx build --platform linux/amd64 \
          -f ./dockerfiles/Dockerfile.server \
          -t ${{ secrets.DOCKER_USERNAME }}/spotify-backend:${{ github.run_number }} \
          .

      - name: Push frontend image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spotify-frontend:${{ github.run_number }}

      - name: Push backend image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spotify-backend:${{ github.run_number }}

      - name: Set up kube config
        run: export KUBECONFIG=$HOME/.kube/config
        
      - name: Check Nodes
        env:
          KUBECONFIG: /home/mateo/.kube/config
        run: kubectl get nodes

      - name: Apply Kubernetes Changes
        env:
          KUBECONFIG: /home/mateo/.kube/config
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          export BUILD_NUMBER=${{ github.run_number }}
          export NAMESPACE=mateo-spotify
          
          # Apply Secrets first
          for FILE in kube/*-secret.yml
          do
              if [ -f "$FILE" ]; then
                  cat $FILE | envsubst | kubectl apply -f -
              fi
          done
          
          # Apply ConfigMaps
          for FILE in kube/*-config.yml
          do
              if [ -f "$FILE" ]; then
                  cat $FILE | envsubst | kubectl apply -f -
              fi
          done
          
          # Apply all other resources
          for FILE in kube/*
          do
              if [[ ! "$FILE" =~ -config.yml$ ]] && [[ ! "$FILE" =~ -secret.yml$ ]]; then
                  cat $FILE | envsubst | kubectl apply -f -
              fi
          done
